server:
  port: 8086
  servlet:
    context-path: /ai
spring:
  application:
    name: AI-service
  ai:
    openai:
      api-key: AIzaSyAfNSoF2zymy7KaQfZzqnfzd92GRytzJks
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash
