server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity_service
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_database"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  services:
    profile: http://localhost:8080/profile

jwt:
  signerKey: "4vCM6CA5NXhXhG+LjHY+PfQRZYGjm13cHoNxVPuDyEYz2XB5SO/8Ko2vCxBkqHeT"
  access-token-duraion: 30
  refresh-token-duraion: 300

