server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity_service
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

app:
  services:
    profile: http://localhost:8080/profile


