server:
  port: 8082
  servlet:
    context-path: /notification


spring:
  application:
    name: notification_service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: com.dongVu1105.post_service.dto.request.ReactEvent:com.dongVu1105.notification_service.dto.request.ReactEvent,com.dongVu1105.identity_service.dto.request.NotificationEvent:com.dongVu1105.notification_service.dto.request.NotificationEvent, com.dongVu1105.post_service.dto.request.CommentEvent:com.dongVu1105.notification_service.dto.request.CommentEvent, com.dongVu1105.profile_service.dto.request.FollowEvent:com.dongVu1105.notification_service.dto.request.FollowEvent
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apikey: 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

app:
  services:
    identity :
      url: http://localhost:8080/identity